#!/bin/bash

if [ ! -d ~/.config/sshtc ]; then
    mkdir ~/.config/sshtc
    chmod 775 ~/.config/sshtc
    touch ~/.config/sshtc/data.json
    chmod 775 ~/.config/sshtc/data.json
    echo "[]" >> ~/.config/sshtc/data.json
fi

$(which python) /usr/local/sshtc/main.py